import type { Metadata } from 'next'
import './globals.css'

import { ClientClickContext } from './components/clickthisbutton'

export const metadata: Metadata = {
  title: 'My Writter',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-skylight text-skyblue">
        <ClientClickContext >
          {children}
        </ClientClickContext>
      </body>
    </html>
  )
}
